name: PowerShell Module Workflow

on:
  push:
    #branches: [ $default-branch ]
    branches: [ feature/github-actions ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello from Octo Organization